---
- hosts: win
  name: Install Windows Updates
  tasks:
    - name: Run Updates
      win_updates:
        category_names: "{{ categories | default(omit) }}"
        reboot: '{{ reboot_server | default(true) }}'
