---
- hosts: update_g1
  name: Install Windows Updates on Group 1
  tasks:
    - name: Run Updates
      win_updates:
        category_names: "{{ categories | default(omit) }}"
        reboot: '{{ reboot_server | default(true) }}'

    - name: Pause for 2 minutes
      ansible.builtin.pause:
        minutes: 2

- hosts: update_g2
  name: Install Windows Updates on Group 2
  tasks:
    - name: Run Updates
      win_updates:
        category_names: "{{ categories | default(omit) }}"
        reboot: '{{ reboot_server | default(true) }}'
